import type { Metadata } from "next";
import "./globals.scss";
import { Header } from "@/models";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body>
        <Header/>
        {children}
      </body>
    </html>
  );
}
