import type { Metadata } from "next";
import "./globals.scss";
import { Header,BottomNavbar,BannerMovie,SliderMovie } from "@/models";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body>
        <Header/>
        <BannerMovie/>
        <SliderMovie/>
      </body>
    </html>
  );
}
